### ISSUE TITLE
Not showing on Package Control ST3

### ISSUE THREAD

**Issue by guidoferreyra** [brew/opentype-feature-bundle#6]
Hi! I can't install via cmd shift P in sublime text 3. Is not present on the list when i search. Any idea why?

**Comment by brew** [comment]
Not sure why it isn't working for you. I can find it with:

cmd + shift + p > Package Control: Install Package > OpenType Feature Bundle

Packages don't show up on the install list if they are already installed. Perhaps you already have it installed?

**Comment by guidoferreyra** [comment]
Sorry Im so dumb!! I've already installed it. I don't know when. 
Thanks!
